### ISSUE TITLE
Custom CSS applied to the editor

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-newsletters#545]
1. Create a new newsletter, open "Styling" sidebar panel, insert:

```css
h1, h2 {
	background:red;
}
```

2. Observe that the `h2`s in the editor get the styles:

<img width="290" alt="image" src="https://user-images.githubusercontent.com/7383192/129360499-6173efc5-3d98-4726-acb5-0f017945a211.png">

---

This is because the scoping does not take into account multi-selector CSS rules, and the scoped custom CSS applied to the page results in:

```css
.edit-post-visual-editor h1, h2 { background: red; }
```
